### PR TITLE
Add support for new controller types

### LINKED ISSUE #11: Only 1 controller works in the game menus
### Describe the bug
Here is a clear and concise description of what the problem is:

Most of the games can only be played in 1 player mode:
Sonic the Hedgehog (2 and 3)
Micro Machines (several versions)
WWF WrestleMania

Mega Bomberman, on the other hand, can be played even in 4 players, but still only one controller works in the game menus. However once the game is started all 4 players can play. In the other games it is impossible to even start the game in 2 player mode without player 2 interaction in the menu.

Would it be possible that there is a difference between assigning the controllers for the in the game menus and for the game itself in the Genesis Plus GX?

## RetroArch Behavior
Here is a clear and concise description of what happens in RetroArch with the same core/game:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

Operating system version/name:

Kodi version: 18.9 (LibreELEC on Amlogic SoC)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by KOPRajs**
Sorry for taking so long. If everything is ok, I'll prepare more PRs for other emulators.

Fixes https://github.com/kodi-game/game.libretro.genplus/issues/11

### CODE REVIEW

**Review by garbear — APPROVED** [review]
Looks good, thanks! After we merge I'll tag and release a new version.

**Comment by KOPRajs** [comment]
Please note that the 4wayplay controller is intentionally only available on port 2.

The 4wayplay actually occupies both port 1 and port 2. If you select 4wayplay on port 1, then setting anything else on port 2 will cancel the 4wayplay on port 1. This way the user is forced to select 4wayplay on port 2 and it actually overrides the port 1 settings.

I've tested all possible configurations and got good results:
1. 2 generic controllers - I can play most of the games for 2 players (Sonic 2, Golden Axe, ...)
2. 1 generic controller in port 1 and the Teamplayer in port 2 - you can play most of the multiplayer games for 4 players (Mega Bomberman, ...) while still possible to play single player games without Teamplayer support
3. 1 generic controller in port 1 and the 4wayplay in port 2 - you can play EA Sports games for 4 players
4. 2 Teamplayers - you can play 8 player games (I haven't tested this as I don't have neither any 8 player game nor 8 controllers available, but it should work)

EDIT: Also note the different button mapping for 3 button and 6 button controllers. This allows to avoid using R1 button in games that only need 3 buttons (X, A, B is used instead of A, B, R1).

**Comment by garbear** [comment]
I gave this a try and confirmed that multiplayer works in Mega Bomberman, tested with a Teamplayer in port 2. Ready to merge?

**Comment by KOPRajs** [comment]
Ready from my side. Once it is merged, I will prepare similar changes for Picodrive.

**Pull request merged**
